version: "3.8"

services:
  backend:
    build: ./material-applications-main/material-applications-main/example-backend
    # volumes:
    #   - "./logs.txt:/usr/src/app/logs.txt"
    ports:
      - 8080:8080
    environment:
      - FRONT_URL=http://172.17.42.29:5000
      - REDIS_HOST=redis
    container_name: "backend"
    depends_on:
      - redis

  frontend:
    build: ./material-applications-main/material-applications-main/example-frontend
    ports:
      - 5000:5000
    environment:
      - REACT_APP_BACKEND_URL=http://172.17.42.29:8080
    container_name: frontend

  redis:
    image: redis
    container_name: redis

